name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
    - name: Restore paket
      run: dotnet tool restore
    - name: Restore packages
      run: dotnet paket restore
    - name: Dependencies restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish .\src\NanoTicTacToe.Clients.Desktop\NanoTicTacToe.Clients.Desktop.fsproj --runtime win-x64 --self-contained true -o .\publish\
    - name: Artifacts
      uses: actions/upload-artifact@v1
      with:
       name: ${{ 'nano-tic-tac-toe-win-x64-v0.0.0.' + github.run_number }}
       path: publish
